# Generated by Django 5.1.6 on 2025-08-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='cryptoprice',
            name='usd_24h_change',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cryptoprice',
            name='usd_24h_vol',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cryptoprice',
            name='usd_market_cap',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='cryptoprice',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddIndex(
            model_name='cryptoprice',
            index=models.Index(fields=['cryptocurrency', 'timestamp'], name='tracker_cry_cryptoc_d0a609_idx'),
        ),
    ]
